services:
  zabbix-proxy:
    image: zabbix/zabbix-proxy-sqlite3:alpine-${ZBX_VERSION}
    container_name: zabbix-proxy
    restart: unless-stopped
    ports:
      - "10051:10051"
    ports:
      - "10051:10051"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./externalscripts:/usr/lib/zabbix/externalscripts:ro
      - ./modules:/var/lib/zabbix/modules:ro
      - ./enc:/var/lib/zabbix/enc:ro
      - ./ssh_keys:/var/lib/zabbix/ssh_keys:ro
      - ./mibs:/var/lib/zabbix/mibs:ro
      - snmptraps:/var/lib/zabbix/snmptraps:rw
    environment:
      #DEBUG_MODE: true
      ZBX_SERVER_HOST: "${ZBX_SERVER_HOST}"
      ZBX_HOSTNAME: "${ZBX_HOSTNAME}"
    stop_grace_period: 30s

  zabbix-agent:
    image: zabbix/zabbix-agent2:alpine-${ZBX_VERSION}
    container_name: zabbix-agent
    restart: unless-stopped
    links:
      - zabbix-proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
      - ./modules:/var/lib/zabbix/modules:ro
      - ./enc:/var/lib/zabbix/enc:ro
      - ./ssh_keys:/var/lib/zabbix/ssh_keys:ro
    environment:
      ZBX_SERVER_HOST: "zabbix-proxy,127.0.0.1"
      ZBX_ACTIVE_ALLOW: "true"
      ZBX_HOSTNAME: "${ZBX_HOSTNAME}"
    privileged: true
    pid: "host"
    stop_grace_period: 5s

volumes:
  snmptraps:
