services:
  zabbix-proxy:
    image: zabbix/zabbix-proxy-sqlite3:latest
    container_name: zabbix-proxy
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./zbx_env/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
      - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
      - ./zbx_env/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
      - snmptraps:/var/lib/zabbix/snmptraps:rw
    environment:
      #DEBUG_MODE: true
      ZBX_SERVER_HOST: "${ZBX_SERVER_HOST}"
      ZBX_HOSTNAME: "${ZBX_HOSTNAME}"
    stop_grace_period: 30s

  zabbix-agent:
    image: zabbix/zabbix-agent2:latest
    container_name: zabbix-agent
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./zbx_env/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
      - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
    environment:
      ZBX_SERVER_HOST: "${ZBX_SERVER_HOST},127.0.0.1"
      ZBX_ACTIVE_ALLOW: "true"
      ZBX_HOSTNAME: "${ZBX_HOSTNAME}"
    privileged: true
    pid: "host"
    stop_grace_period: 5s

volumes:
  snmptraps:
